'use client'
import Nav from "../components/nav";

export default function Home() {
  return (
    <main className="bg-background relative px-4 pb-4">
      <Nav />
      <p className="text-lg font-medium text-primary">
        -coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-coming soon-
      </p>
    </main>
  );
}
